#!/usr/bin/env bash
#
# rebuild_analysis.sh
# ===================
# Rebuilds a clean analysis dataset for LLM-Agent-IOT from all_runs.zip.
#
#   ./rebuild_analysis.sh
#
# Run it from the repository root (the folder containing all_runs.zip
# and physical_impact.py). Nothing existing is modified or deleted:
# data/results/ is left exactly as it is.
#
# What it produces:
#   data/analysis/*.json     12 curated files, physical_impact corrected
#   data/analysis/README.md  what was included, excluded, and why
#
# Statistics, tables and figures come afterwards, from paper_analysis.py.
#
set -euo pipefail

[[ -f all_runs.zip ]]        || { echo "ERROR: all_runs.zip not found. Run this from the repo root."; exit 1; }
[[ -f physical_impact.py ]]  || { echo "ERROR: physical_impact.py not found. Run this from the repo root."; exit 1; }

WORK=".rebuild_tmp"
rm -rf "$WORK" data/analysis
mkdir -p "$WORK/raw" data/analysis

echo "[1/3] Extracting the 12 genuine executions from all_runs.zip"
FILES=(
  20260714_195521   # GPT-5.5            exec 1
  20260716_214008   # GPT-5.5            exec 2
  20260715_155122   # Claude Sonnet 4.5  exec 1
  20260715_181031   # Claude Sonnet 4.5  exec 2
  20260714_185900   # Gemini 2.5 Flash   exec 1   <-- recovered, see README
  20260714_200243   # Gemini 2.5 Flash   exec 2
  20260715_142509   # Gemini 3.5 Flash   exec 1
  20260715_153624   # Gemini 3.5 Flash   exec 2
  20260716_163215   # defense: majority voting
  20260715_164233   # defense: reputation system
  20260715_180744   # defense: confidence weighted
  20260716_173637   # defense: trust clipping
)
for f in "${FILES[@]}"; do
  unzip -o -j -q all_runs.zip "cascade_results_$f.json" -d "$WORK/raw"
done
echo "      $(ls -1 "$WORK/raw" | wc -l) files extracted"

echo "[2/3] Correcting physical_impact (star-hub double counting)"
# NOTE: physical_impact.py only globs cascade_results_*.json, so the rename
# has to happen AFTER this step, never before.
python3 physical_impact.py --in "$WORK/raw" --out "$WORK/fixed"

echo "[3/3] Renaming into data/analysis/"
python3 - "$WORK/fixed" << 'PY'
import shutil, sys, pathlib
src = pathlib.Path(sys.argv[1])
M = {'20260714_195521':'gpt55_exec1',      '20260716_214008':'gpt55_exec2',
     '20260715_155122':'claude45_exec1',   '20260715_181031':'claude45_exec2',
     '20260714_185900':'gemini25_exec1',   '20260714_200243':'gemini25_exec2',
     '20260715_142509':'gemini35_exec1',   '20260715_153624':'gemini35_exec2',
     '20260716_163215':'defense_majority', '20260715_164233':'defense_reputation',
     '20260715_180744':'defense_confidence','20260716_173637':'defense_trust'}
for k, v in M.items():
    shutil.copy(src / f'cascade_results_{k}.json', f'data/analysis/{v}.json')
print(f'      {len(M)} files written')
PY

cat > data/analysis/README.md << 'EOF'
# Curated analysis dataset

Generated by `rebuild_analysis.sh` from `all_runs.zip`. Every file has been
passed through `physical_impact.py`: P is recomputed from `propagation_path`,
removing the star-hub double counting; `physical_impact_original` is kept as an
audit trail.

## Baseline: 2 independent executions per model, 25 attacked runs each

| File | Source timestamp | Model |
|---|---|---|
| gpt55_exec1.json | 20260714_195521 | GPT-5.5 |
| gpt55_exec2.json | 20260716_214008 | GPT-5.5 |
| claude45_exec1.json | 20260715_155122 | Claude Sonnet 4.5 |
| claude45_exec2.json | 20260715_181031 | Claude Sonnet 4.5 |
| gemini25_exec1.json | 20260714_185900 | Gemini 2.5 Flash (see OPEN ASSUMPTION) |
| gemini25_exec2.json | 20260714_200243 | Gemini 2.5 Flash |
| gemini35_exec1.json | 20260715_142509 | Gemini 3.5 Flash |
| gemini35_exec2.json | 20260715_153624 | Gemini 3.5 Flash |

## Defenses: Gemini 3.5 Flash, one execution, 25 attacked runs per topology

defense_majority.json, defense_reputation.json, defense_confidence.json,
defense_trust.json. The baseline for defense comparisons is
gemini35_exec1 + gemini35_exec2 pooled.

## OPEN ASSUMPTION

gemini25_exec1.json (20260714_185900) is treated as a valid independent
execution. It was recovered from all_runs.zip and had never been placed in
data/results/. Supporting evidence: 250 complete runs, 125 intercepts and 104
attack attempts (in range with every other file), no `checkpoint` flag, and a
47-minute duration ending 64 minutes before the next execution, matching the
end-then-relaunch pattern of Gemini 3.5 (6 min) and Claude (11 min).
This has NOT been confirmed against lab logs. If it proves to be a pilot run,
Gemini 2.5 has only ONE execution and must be excluded from the run-to-run
variability analysis.

## Excluded, and why

- cascade_results_gemini25_run1.json: byte-identical checkpoint copy of 20260714_200243
- cascade_results_gpt55_run1.json: checkpoint copy of 20260714_195521 (the original is used)
- statistics.json: stale per-batch artefact, contradicts data/figures/stats_tests.json
- all *.csv exports: incomplete (the Gemini 2.5 export stops at 36 of 250 rows)
EOF

rm -rf "$WORK"

echo
echo "Done."
echo "  data/analysis/  $(ls -1 data/analysis/*.json | wc -l) json files + README.md"
echo
echo "Next: python3 paper_analysis.py"